/**
 * Bibliothèque pédagogique « Examens paracliniques » — SantéOnline.
 * Contenu de référence rédigé à visée d'apprentissage et d'information médicale.
 * ⚠️ Les valeurs indiquées sont des REPÈRES usuels : elles varient selon le
 * laboratoire, la méthode, l'âge, le sexe et le contexte clinique.
 * Toujours privilégier les valeurs de référence du laboratoire d'analyse.
 * Une anomalie n'est jamais, à elle seule, un diagnostic.
 */
export type ExamCategory = "biologie" | "imagerie" | "cardiologie" | "explorations" | "endoscopie" | "anapath";

export interface ExamSeed {
  slug: string;
  name: string;
  category: ExamCategory;
  definition: string;
  objective: string;
  indications: string;
  contraindications: string;
  preparation: string;
  procedureText: string;
  materials: string;
  parameters: string;
  referenceValues: string;
  interpretation: string;
  anomalies: string;
  limitations: string;
  references: string;
  updatedOn: string;
}

export const EXAM_SEED: ExamSeed[] = [
  /* ==================== BIOLOGIE MÉDICALE ==================== */
  {
    slug: "nfs",
    name: "NFS (Numération Formule Sanguine)",
    category: "biologie",
    definition: "Analyse quantitative et qualitative des cellules du sang : globules rouges, globules blancs, plaquettes, avec hémoglobine, hématocrite et indices érythrocytaires.",
    objective: "Dépister une anémie, une infection, une inflammation, un saignement ou une maladie hématologique ; surveiller un traitement (chimiothérapie, antipaludéens…).",
    indications: "Fatigue, pâleur, fièvre, infections, bilan pré-opératoire, suspicion d'anémie ou de paludisme, suivi de maladies chroniques, chimiothérapie.",
    contraindications: "Aucune contre-indication. Précaution : risque d'hématome au point de ponction chez les patients anticoagulés.",
    preparation: "Aucun jeûne nécessaire. Signaler toute transfusion récente ou traitement en cours.",
    procedureText: "Prélèvement veineux au pli du coude (quelques mL), indolore hors piqûre. Résultats généralement en quelques heures.",
    materials: "Garrot, aiguille, tube EDTA (violet) ; automate d'hématologie au laboratoire.",
    parameters: "GB, GR, Hb, Hct, VGM, TCMH, CCMH, plaquettes, formule leucocytaire (PNN, lymphocytes, monocytes…), réticulocytes sur demande.",
    referenceValues: "Repères usuels : GB 4–10 G/L ; Hb homme 13–17 g/dL, femme 12–16 g/dL ; Hct H 40–54 %, F 37–47 % ; plaquettes 150–400 G/L ; VGM 80–100 fL. Toujours se référer aux valeurs du laboratoire.",
    interpretation: "Hb basse = anémie ; GB élevés = infection/inflammation ; GB bas = leucopénie (virale, médicamenteuse) ; plaquettes basses = thrombopénie (risque hémorragique < 50 G/L). La VGM oriente : microcytose (fer), macrocytose (B12/folates), normocytose (aiguë, chronique).",
    anomalies: "Anémies ferriprive ou par carence (B12, folates), paludisme (thrombopénie fréquente), infections bactériennes (PNN élevés), virales ou typhoïde (leucopénie), hémopathies, effets médicamenteux.",
    limitations: "Analyse quantitative : elle ne donne pas la cause à elle seule ; variations physiologiques (grossesse, effort, altitude) ; à interpréter avec la clinique et, si besoin, un frottis sanguin.",
    references: "HAS ; Société Française d'Hématologie (SFH) ; OMS — seuils d'anémie.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "glycemie",
    name: "Glycémie",
    category: "biologie",
    definition: "Mesure de la concentration de glucose dans le sang, principal carburant de l'organisme, régulée par l'insuline.",
    objective: "Dépister et surveiller le diabète, rechercher une hypoglycémie, ajuster un traitement antidiabétique.",
    indications: "Dépistage du diabète (polyurie, polydipsie, amaigrissement), suivi du diabétique, malaises, grossesse (dépistage du diabète gestationnel), urgences métaboliques.",
    contraindications: "Aucune. Précision : le glucomètre capillaire est indicatif, le dosage de laboratoire fait foi.",
    preparation: "Glycémie À JEUN : 8 à 12 h sans alimentation (eau permise). La glycémie postprandiale se mesure 2 h après le début du repas.",
    procedureText: "Prélèvement veineux (tube gris au fluorure) ou piqûre capillaire au glucomètre. Noter l'heure du dernier repas.",
    materials: "Tube au fluorure de sodium (anti-glycolyse), glucomètre et bandelettes.",
    parameters: "Glucose sanguin en g/L (ou mmol/L) ; éventuellement HGPO 75 g pour le dépistage.",
    referenceValues: "Repères usuels : à jeun 0,70–1,10 g/L (3,9–6,1 mmol/L) ; postprandiale < 1,40 g/L. Diabète (OMS) : glycémie à jeun ≥ 1,26 g/L à 2 reprises, ou ≥ 2,00 g/L à HGPO. Hypoglycémie : < 0,70 g/L.",
    interpretation: "Entre 1,10 et 1,26 g/L à jeun = hyperglycémie modérée (pré-diabète) ; ≥ 1,26 g/L deux fois = diabète. Une glycémie isolée élevée sous stress ne suffit pas : confirmer.",
    anomalies: "Diabète de type 1 ou 2, diabète gestationnel, pré-diabète, hypoglycémies médicamenteuses, insulinome (rare), insuffisance surrénale.",
    limitations: "Valeur instantanée : ne reflète pas l'équilibre sur la durée (voir HbA1c) ; erreurs possibles si tube non fluoré conservé longtemps (glycolyse).",
    references: "OMS / ADA — critères diagnostiques du diabète ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "hba1c",
    name: "HbA1c (Hémoglobine glyquée)",
    category: "biologie",
    definition: "Mesure du pourcentage d'hémoglobine liée au glucose, reflétant la glycémie MOYENNE des 2 à 3 derniers mois.",
    objective: "Diagnostiquer le diabète et évaluer l'équilibre glycémique sur la durée, indépendamment du repas du jour.",
    indications: "Dépistage et confirmation du diabète, suivi trimestriel/semestriel du diabétique, évaluation de l'observance.",
    contraindications: "Aucune. Prudence d'interprétation : anémies hémolytiques, drépanocytose (fréquente en Afrique de l'Ouest), transfusion récente ou grossesse peuvent fausser le résultat.",
    preparation: "Aucun jeûne nécessaire — avantage majeur.",
    procedureText: "Prélèvement veineux simple sur tube EDTA. Dosage toutes les 8–12 semaines chez le diabétique.",
    materials: "Tube EDTA ; méthodes HPLC ou immunoturbidimétrie au laboratoire.",
    parameters: "HbA1c en pourcentage d'hémoglobine totale (et mmol/mol en unités IFCC).",
    referenceValues: "Repères usuels : < 5,7 % normal ; 5,7–6,4 % pré-diabète ; ≥ 6,5 % diabète. Objectif thérapeutique fréquent : < 7 % (à individualiser).",
    interpretation: "Chaque point d'HbA1c correspond à environ 0,30 g/L de glycémie moyenne. 8 % ≈ glycémie moyenne 1,83 g/L.",
    anomalies: "Diabète mal équilibré, pré-diabète ; faux résultats bas (hémolyse, saignement récent) ou hauts (carence martiale sévère).",
    limitations: "Ne montre pas les variations quotidiennes ni les hypoglycémies ; inutilisable seule en cas d'hémoglobinopathie (préférer fructosamine).",
    references: "ADA Standards of Care ; HAS — suivi du diabète de type 2.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "crp",
    name: "CRP (Protéine C-Réactive)",
    category: "biologie",
    definition: "Protéine de l'inflammation synthétisée par le foie, dont le taux sanguin augmente rapidement en cas d'inflammation ou d'infection aiguë.",
    objective: "Détecter une inflammation aiguë, orienter vers une origine bactérienne, suivre l'efficacité d'un traitement anti-infectieux.",
    indications: "Fièvre inexpliquée, suspicion d'infection bactérienne, suivi post-opératoire, maladies inflammatoires, arthrites.",
    contraindications: "Aucune. Non spécifique : toujours contextualiser.",
    preparation: "Pas de jeûne nécessaire.",
    procedureText: "Prélèvement veineux standard (tube sec ou hépariné). Réponse rapide : la CRP monte en 6–12 h et redescend vite après guérison.",
    materials: "Tube sec/héparine ; dosage immunoturbidimétrique.",
    parameters: "CRP en mg/L. Variante « CRP-us » (ultrasensible) pour le risque cardiovasculaire.",
    referenceValues: "Repères usuels : < 5–6 mg/L en l'absence d'inflammation ; 10–40 inflammation modérée ou virale ; > 50–100 évocateur d'infection bactérienne ; > 200 infection sévère (sepsis).",
    interpretation: "Une CRP qui décroît sous traitement est bon signe. CRP normale n'élimine pas une infection débutante ou localisée.",
    anomalies: "Infections bactériennes, paludisme (modérément élevée), maladies auto-immunes, cancers, infarctus, obésité (CRP-us légèrement élevée).",
    limitations: "Aucune spécificité d'organe ni de germe ; ne remplace ni la clinique ni les prélèvements microbiologiques.",
    references: "HAS — place de la CRP en ambulatoire ; SPILF (antibiothérapie).",
    updatedOn: "2026-08-15",
  },
  {
    slug: "vs",
    name: "VS (Vitesse de Sédimentation)",
    category: "biologie",
    definition: "Mesure de la vitesse de chute des globules rouges dans un tube vertical en 1 heure ; témoin indirect de l'inflammation.",
    objective: "Dépister une inflammation chronique ou aiguë et suivre son évolution, notamment dans les maladies inflammatoires systémiques.",
    indications: "Douleurs inflammatoires, fièvre prolongée, suspicion de maladie de Horton, polymyalgie rhumatismale, suivi de maladies rhumatismales.",
    contraindications: "Aucune. Nombreux facteurs de variation non inflammatoires.",
    preparation: "Pas de jeûne. Femmes : grossesse et règles augmentent la VS.",
    procedureText: "Prélèvement veineux sur tube citrate (noir) ; lecture automatique au laboratoire à 1 heure, parfois 2 heures.",
    materials: "Tube citraté ; lecteur de VS automatisé (méthode de Westergren modifiée).",
    parameters: "VS à la 1re heure en mm (parfois 2e heure).",
    referenceValues: "Repères usuels : homme < 15 mm/h ; femme < 20 mm/h ; augmente avec l'âge (formule : âge/2 chez l'homme). Très élevée > 100 mm/h = Horton, cancer, infection sévère, myélome.",
    interpretation: "Inflammation persistante (monte et descend LENTEMENT contrairement à la CRP) ; utile au suivi chronique plus qu'au diagnostic aigu.",
    anomalies: "Infections chroniques (tuberculose), vascularites, cancers, hémopathies, anémies (artefact d'élévation).",
    limitations: "Très peu spécifique ; augmentée par l'anémie, la grossesse, l'âge ; diminuée par la polyglobulie. Souvent couplée à la CRP.",
    references: "HAS ; SNFMI — fièvres prolongées ; recommandations rhumatologiques.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "creatinine",
    name: "Créatinine sanguine",
    category: "biologie",
    definition: "Déchet issu de la dégradation musculaire, éliminé exclusivement par les reins : son taux reflète la fonction de filtration rénale.",
    objective: "Évaluer la fonction rénale, calculer le débit de filtration glomérulaire (DFG), dépister l'insuffisance rénale, adapter les doses de médicaments.",
    indications: "HTA, diabète, œdèmes, troubles urinaires, avant injection de produit de contraste ou médicaments néphrotoxiques, suivi de l'insuffisant rénal.",
    contraindications: "Aucune. Interpréter selon la masse musculaire (sportifs, dénutrition, personnes âgées).",
    preparation: "Pas de jeûne strict ; éviter un effort musculaire intense et une grosse consommation de viande la veille.",
    procedureText: "Prélèvement veineux simple. Le DFG est calculé automatiquement à partir de la créatinine, de l'âge, du sexe (formule CKD-EPI).",
    materials: "Tube sec ou héparine.",
    parameters: "Créatininémie en µmol/L ; DFG estimé en mL/min/1,73 m².",
    referenceValues: "Repères usuels : homme 70–115 µmol/L, femme 55–100 µmol/L. DFG normal ≥ 90 ; IRC si DFG < 60 pendant plus de 3 mois ; IRA si élévation aiguë.",
    interpretation: "Une créatinine qui double = fonction rénale très altérée. Une petite élévation chez le sujet âgé signifie déjà une baisse marquée du DFG.",
    anomalies: "Insuffisance rénale aiguë (déshydratation, infection, médicaments) ou chronique (HTA, diabète, glomérulonéphrite), obstruction urinaire, rhabdomyolyse.",
    limitations: "Peu sensible au début (monte tardivement) ; dépend de la masse musculaire ; compléter par ionogramme, urée et EBU/protéinurie.",
    references: "KDIGO — classification de l'IRC ; HAS ; SFD (diabète et rein).",
    updatedOn: "2026-08-15",
  },
  {
    slug: "uree",
    name: "Urée sanguine",
    category: "biologie",
    definition: "Produit final du métabolisme des protéines, fabriqué par le foie et éliminé par les reins.",
    objective: "Apprécier la fonction rénale et hépatique, rechercher une déshydratation ou un catabolisme protéique excessif.",
    indications: "Vomissements/diarrhées abondantes, suspicion d'insuffisance rénale, hémorragie digestive, hypercatabolisme, suivi de dialyse.",
    contraindications: "Aucune.",
    preparation: "Pas de jeûne nécessaire.",
    procedureText: "Prélèvement veineux, souvent couplé à la créatinine : le rapport urée/créatinine éclaire le mécanisme.",
    materials: "Tube sec ou héparine.",
    parameters: "Urée en mmol/L (ou g/L) ; rapport urée/créatinine.",
    referenceValues: "Repères usuels : 2,5–7,5 mmol/L (0,15–0,45 g/L).",
    interpretation: "Urée élevée avec créatinine normale ou peu élevée → déshydratation, hémorragie digestive haute, hypercatabolisme. Urée et créatinine élevées ensemble → atteinte rénale. Urée basse → insuffisance hépatocellulaire, grossesse, dénutrition.",
    anomalies: "Insuffisance rénale, déshydratation sévère, saignement digestif, fièvre prolongée, corticoïdes ; baisse : hépatopathie sévère, régime pauvre en protéines.",
    limitations: "Influencée par l'alimentation protéique et l'hydratation ; jamais interprétée isolément sans la créatinine.",
    references: "KDIGO ; HAS — évaluation de la fonction rénale.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "ionogramme",
    name: "Ionogramme sanguin (Na⁺, K⁺, Cl⁻, bicarbonates)",
    category: "biologie",
    definition: "Dosage des principaux électrolytes du sang, essentiels au fonctionnement des muscles, du cœur et de l'équilibre acido-basique.",
    objective: "Dépister et corriger les troubles hydro-électrolytiques, en particulier les dyskaliémies potentiellement mortelles (troubles du rythme cardiaque).",
    indications: "Déshydratation, vomissements, diarrhées profuses (choléra…), insuffisance rénale ou cardiaque, diurétiques, malaises, troubles du rythme, confusion.",
    contraindications: "Aucune. Attention à l'hémolyse du tube qui surestime le potassium.",
    preparation: "Pas de jeûne. Préciser les traitements en cours (diurétiques, IEC…).",
    procedureText: "Prélèvement veineux sans garrot prolongé, analyse rapide；le potassium reste la valeur d'urgence vitale.",
    materials: "Tube héparine ; analyseur d'électrolytes (électrodes ionosélectives).",
    parameters: "Sodium, potassium, chlore, bicarbonates (réserve alcaline), ± rapport Na/K.",
    referenceValues: "Repères usuels : Na 135–145 mmol/L ; K 3,5–5,0 mmol/L (urgence < 3,0 ou > 6,0) ; Cl 98–106 mmol/L ; HCO₃⁻ 22–26 mmol/L.",
    interpretation: "Hyponatrémie : dilution ou pertes ; hypernatrémie : déshydratation. Hypokaliémie : diarrhées, diurétiques ; hyperkaliémie : insuffisance rénale, hémolyse du prélèvement, acidose. Bicarbonates bas : acidose métabolique.",
    anomalies: "Déshydratation, syndrome cholériforme, insuffisance rénale, insuffisance surrénale (K élevé, Na bas), diabète déséquilibré, alcaloses.",
    limitations: "Photographie instantanée ; l'hémolyse fausse le K ; répéter tout chiffre critique avant correction intraveineuse.",
    references: "HAS — prise en charge des déshydratations ; ERCAT/LVTS electrolytes.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "bilan-hepatique",
    name: "Bilan hépatique (ASAT, ALAT, PAL, GGT, bilirubine)",
    category: "biologie",
    definition: "Ensemble de dosages évaluant les cellules et les voies biliaires du foie : transaminases, phosphatases alcalines, GGT, bilirubine, ± TP/albumine.",
    objective: "Dépister une hépatite, une cholestase (obstacle biliaire) ou une insuffisance hépatique ; surveiller un traitement hépatotoxique.",
    indications: "Ictère (jaunisse), urines foncées, douleur de l'hypochondre droit, fatigue, alcoolisme, hépatite B (très fréquente en Afrique de l'Ouest), automédication, cirrhose.",
    contraindications: "Aucune.",
    preparation: "Jeûne de 8 h recommandé (bili). Pas d'alcool les jours précédents.",
    procedureText: "Prélèvement veineux au laboratoire ; le TP (coagulation) évalue la fonction de synthèse du foie.",
    materials: "Tube sec/héparine.",
    parameters: "ASAT, ALAT, PAL, GGT, bilirubine totale/conjuguée, ± albumine et TP.",
    referenceValues: "Repères usuels : ASAT et ALAT < 35–40 UI/L ; PAL 40–130 UI/L ; GGT H < 55, F < 38 UI/L ; bilirubine totale < 17 µmol/L (ictère clinique > 40).",
    interpretation: "Transaminases très élevées (× 10) = cytolyse aiguë (hépatite virale, toxique). PAL + GGT élevés = cholestase. Bilirubine conjuguée élevée = obstacle. TP effondré + albumine basse = insuffisance hépatocellulaire.",
    anomalies: "Hépatites virales (A, B, C, E), paludisme ictérique, hépatite médicamenteuse, alcool, stéatose (surcharge pondérale), lithiase biliaire, cancers.",
    limitations: "ALAT élevée n'indique pas la cause ; n'hésitez pas à compléter par sérologies et échographie hépatique.",
    references: "HAS — ictère et hépatites ; APASL/WHO — VHB en Afrique.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "bilan-lipidique",
    name: "Bilan lipidique (cholestérol, triglycérides)",
    category: "biologie",
    definition: "Dosage des graisses circulantes : cholestérol total, HDL (« bon »), LDL (« mauvais ») et triglycérides.",
    objective: "Évaluer le risque cardiovasculaire (infarctus, AVC) et guider la prévention ou le traitement hypolipémiant.",
    indications: "HTA, diabète, tabagisme, surpoids, antécédents familiaux précoces, suivi des statines, dépistage à partir de 40 ans.",
    contraindications: "Aucune. Reporter en cas d'événement aigu récent (résultats temporairement faux).",
    preparation: "Jeûne de 12 h classiquement recommandé (surtout pour les triglycérides) ; eau permise.",
    procedureText: "Prélèvement veineux au laboratoire ; LDL calculé ou dosé.",
    materials: "Tube sec.",
    parameters: "Cholestérol total, HDL-C, LDL-C, triglycérides ; ± rapport CT/HDL.",
    referenceValues: "Repères usuels : CT < 2,00 g/L ; LDL < 1,60 g/L (cible plus basse selon le risque : < 1,00 voire < 0,70 g/L si très haut risque) ; HDL > 0,40 g/L ; TG < 1,50 g/L ; jeûne strict si TG > 4 g/L.",
    interpretation: "Le LDL est la cible principale : plus le risque cardiovasculaire global est élevé, plus la cible est basse. TG très élevés (> 10 g/L) = risque de pancréatite aiguë.",
    anomalies: "Hypercholestérolémies familiales, syndrome métabolique, hypothyroïdie, diabète, néphropathie, alcool.",
    limitations: "Le risque se juge sur l'ENSEMBLE des facteurs (âge, TA, tabac…) ; un chiffre isolé ne justifie pas toujours un médicament.",
    references: "ESC/EAS — dyslipidémies ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "bilan-thyroidien",
    name: "Bilan thyroïdien (TSH, T4L, T3L)",
    category: "biologie",
    definition: "Dosage des hormones régulant la glande thyroïde, chef d'orchestre du métabolisme.",
    objective: "Dépister et surveiller hypo et hyperthyroïdie ; équilibrer un traitement thyroïdien.",
    indications: "Prise ou perte de poids inexpliquée, frilosité ou sueurs, tachycardie, tremblements, fatigue, goître, troubles des règles, grossesse.",
    contraindications: "Aucune. Signaler biotine (compléments) : fausse de nombreux dosages.",
    preparation: "Pas de jeûne ; arrêter la biotine 48–72 h avant si possible.",
    procedureText: "Prélèvement veineux ; TSH en première intention, T4L/T3L si TSH anormale.",
    materials: "Tube sec ; dosage immunologique.",
    parameters: "TSH (mUI/L), T4 libre, T3 libre ; ± anticorps anti-TPO, échographie.",
    referenceValues: "Repères usuels : TSH 0,4–4,0 mUI/L ; T4L 9–19 pmol/L (variable selon la méthode).",
    interpretation: "TSH élevée + T4L basse = hypothyroïdie ; TSH effondrée + T4L élevée = hyperthyroïdie ; TSH seule modifiée = forme « fruste » (subclinique) à surveiller.",
    anomalies: "Hypothyroïdie auto-immune (Hashimoto), hyperthyroïdie (Basedow), goître endémique (carence en iode), nodules, thyroïdites.",
    limitations: "La TSH seule suffit au dépistage mais pas au diagnostic complet ; valeurs propres à la grossesse par trimestre.",
    references: "HAS — dysthyroïdies ; American Thyroid Association.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "bilan-coagulation",
    name: "Bilan de coagulation (TP, INR, TCA)",
    category: "biologie",
    definition: "Évaluation de la fluidité du sang et de sa capacité à former un caillot via les facteurs de coagulation.",
    objective: "Dépister un trouble de la coagulation, surveiller les anticoagulants (warfarine/fluindione), sécuriser avant une chirurgie ou une biopsie.",
    indications: "Saignements anormaux, hématomes spontanés, pré-opératoire, traitement par AVK, insuffisance hépatique, thromboses récidivantes.",
    contraindications: "Aucune. Respecter l'heure exacte de prise de l'anticoagulant pour l'INR.",
    preparation: "Pas de jeûne ; noter la dernière dose d'AVK (même heure chaque jour).",
    procedureText: "Prélèvement veineux sur tube citraté (bleu), tube rempli exactement au trait de jauge, analyse rapide.",
    materials: "Tube au citrate de sodium (bleu).",
    parameters: "TP (taux de prothrombine, %), INR, TCA (temps de céphaline activée), ± fibrinogène.",
    referenceValues: "Repères usuels : TP 70–100 % ; INR 0,9–1,2 sans anticoagulant (cible sous AVK : 2–3, parfois 2,5–3,5) ; TCA : ratio patient/témoin ≤ 1,2 (≈ 30–40 s) ; fibrinogène 2–4 g/L.",
    interpretation: "INR trop haut = risque hémorragique (réduire l'AVK) ; INR trop bas = risque thrombotique. TCA allongé isolé → héparine, hémophilie, inhibiteur. TP bas + plaquettes basses + fibrinogène bas = CIVD (urgence).",
    anomalies: "Hémophilie, maladie de Willebrand, insuffisance hépatique, carence en vitamine K, CIVD (sepsis, paludisme grave), thrombophilies.",
    limitations: "Ne prédit pas le saignement à lui seul ; l'hémolyse ou un tube mal rempli fausse tout ; renouveler si doute avant chirurgie.",
    references: "HAS — surveillance des AVK ; GFHT.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "ferritine",
    name: "Ferritine",
    category: "biologie",
    definition: "Protéine de stockage du fer : son taux reflète les réserves en fer de l'organisme.",
    objective: "Diagnostiquer une carence martiale (cause n°1 d'anémie) ou une surcharge en fer ; faire la part entre anémie inflammatoire et ferriprive.",
    indications: "Anémie microcytaire, fatigue, règles abondantes, dénutrition, grossesse, suspicion d'hémochromatose.",
    contraindications: "Aucune. Prudence : ferritine élevée en cas d'inflammation même si carence vraie — coupler CRP.",
    preparation: "Pas de jeûne. Prescrire la CRP en même temps pour interpréter correctement.",
    procedureText: "Prélèvement veineux simple.",
    materials: "Tube sec ; dosage immunochimique.",
    parameters: "Ferritinémie en µg/L ; ± fer sérique, transferrine, coefficient de saturation.",
    referenceValues: "Repères usuels : femme 20–200 µg/L ; homme 30–300 µg/L. Carence martiale : < 15–30 µg/L (ou < 70 si inflammation) ; surcharge : > 400–1 000 µg/L.",
    interpretation: "Ferritine basse = carence martiale certaine quelle que soit l'hémoglobine. Ferritine haute + CRP élevée = difficulté d'interprétation (le taux monte avec l'inflammation).",
    anomalies: "Carence en fer (saignements chroniques, règles, parasitoses), hémochromatose, hyperferritinémie inflammatoire, hémoglobinopathies transfusées.",
    limitations: "Protéine de phase aiguë : jamais seule sans CRP ; ne localise pas le saignement (rechercher la cause : digestive, gynécologique…).",
    references: "OMS — carence en fer ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "serologies",
    name: "Sérologies infectieuses (VIH, VHB, VHC, syphilis…)",
    category: "biologie",
    definition: "Détection d'anticorps et/ou d'antigènes témoins d'un contact ou d'une infection virale ou bactérienne (VIH, hépatites B et C, syphilis, rubéole, toxoplasmose selon contexte).",
    objective: "Dépister une infection transmissible avant don du sang, grossesse, chirurgie ; diagnostiquer une hépatite ou une MST ; guider la prévention (vaccination, traitement).",
    indications: "Dépistage VIH/VHB/VHC, bilan prénatal, avant transfusion ou greffe, exposition au sang (AES), partenaire contaminant, ictère.",
    contraindications: "Aucune technique. OBLIGATION : information du patient et consentement (VIH), stricte confidentialité des résultats.",
    preparation: "Pas de jeûne ; temps d'écoute et de recueil du consentement ; cyphage/anonymisation si demandé.",
    procedureText: "Prélèvement veineux ; tests rapides de diagnostic (TROD) possibles au point de service, confirmation au laboratoire.",
    materials: "Tube sec ; tests ELISA, TROD, PCR (charge virale) en 2e intention.",
    parameters: "Selon la maladie : AgHBs, Ac anti-VHC, VIH p24/Ac (test 4e génération), TPHA/VDRL, IgG/IgM rubéole et toxoplasmose.",
    referenceValues: "Repères usuels : résultat « négatif » = pas de contact (hors fenêtre silencieuse de 2 à 12 semaines) ; « positif » = à CONFIRMER par un second test de référence avant toute annonce.",
    interpretation: "IgM = infection récente ; IgG seuls = immunité ancienne ou vaccinale (VHB : Ac anti-HBs protecteurs ≥ 10 UI/L). Fenêtre sérologique : un test négatif précoce ne suffit pas — refaire à 6–12 semaines.",
    anomalies: "VIH-1/2, hépatite B chronique (AgHBs persistant > 6 mois), VHC, syphilis, co-infections ; faux positifs possibles des TROD.",
    limitations: "Temporalité (fenêtre), faux positifs/négatifs, nécessité de confirmation ; le résultat engage un accompagnement (annonce, traitement, prévention).",
    references: "OMS — dépistage VIH/VHB en Afrique ; HAS ; PNLS Togo.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "ecbu",
    name: "ECBU (Examen Cytobactériologique des Urines)",
    category: "biologie",
    definition: "Analyse microscopique et culture des urines pour déceler une infection urinaire (leucocytes, bactéries) et identifier le germe responsable.",
    objective: "Confirmer une infection urinaire et choisir l'antibiotique adapté grâce à l'antibiogramme — arme contre l'antibiorésistance.",
    indications: "Brûlures mictionnelles, fièvre sans point d'appel (nourrisson, personne âgée), douleurs lombaires, grossesse (dépistage systématique), sonde urinaire, récidives.",
    contraindications: "Aucune. Prélever AVANT tout antibiotique quand c'est possible.",
    preparation: "Toilette intime soigneuse à l'eau et au savon, recueillir le « milieu du jet » (jetée la première urine), flacon stérile, acheminer rapidement (< 2 h ou 4 °C).",
    procedureText: "Microscopie (leucocytes, hématies, bactéries) + bandelette (nitrites, leucocytes) + culture 24–48 h avec numération des germes.",
    materials: "Flacon stérile, gants ; milieu de culture au laboratoire.",
    parameters: "Leucocyturie (/mm³), hématurie, bactériurie, germe identifié avec comptage (UFC/mL) et antibiogramme.",
    referenceValues: "Repères usuels : leucocytes < 10/mm³ ; bactériurie significative ≥ 10⁵ UFC/mL (seuils adaptés : 10³–10⁴ si pyurie associée ou symptômes) ; nitrites = négatifs en temps normal.",
    interpretation: "Leucocyturie + bactériurie = infection urinaire confirmée ; germe seul sans leucocytes = contamination probable (refaire proprement) ; leucocytes seuls = urines stériles (tuberculose, chlamydiae…).",
    anomalies: "Cystite, pyélonéphrite, urétrite, prostatite, bactériurie asymptomatique de la grossesse (à traiter !), contamination du prélèvement.",
    limitations: "Sensible aux conditions de recueil (contaminations fréquentes) ; l'antibiogramme guide mais ne remplace pas le jugement clinique (point d'appel, terrain).",
    references: "HAS — infections urinaires de l'adulte et de l'enfant ; EAU ; OMS antibiorésistance.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "hemoculture",
    name: "Hémoculture",
    category: "biologie",
    definition: "Mise en culture du sang pour rechercher la présence de bactéries ou de levures dans le sang (bactériémie, septicémie, endocardite, fièvre typhoïde).",
    objective: "Identifier un germe circulant dans le sang et tester ses antibiotiques — examen clé des fièvres graves et prolongées.",
    indications: "Fièvre élevée avec frissons, suspicion de sepsis ou de choc septique, fièvre prolongée (typhoïde !), endocardite, infection sur cathéter, immunodépression.",
    contraindications: "Aucune. Ne jamais retarder un antibiotique vital : prélever PUIS traiter immédiatement si urgence.",
    preparation: "Asepsie rigoureuse de la peau (antiseptique alcoolique), idéalement au pic fébrile, AVANT antibiotiques ; 2 à 3 paires de flacons, sites distincts.",
    procedureText: "Prélèvements veineux dédiés injectés dans des flacons d'hémoculture ; incubation 24–72 h ; si positif : identification + antibiogramme.",
    materials: "Flacons aérobie et anaérobie, antiseptique, gants stériles ; automate de détection.",
    parameters: "Positivité (oui/non), délai de positivité, germe identifié, antibiogramme ; un seul flacon positif à un coccus cutané = souvent contamination.",
    referenceValues: "Repères usuels : stérilité du sang en temps normal ; toute hémoculture positive vraie est anormale et doit être analysée (contamination vs vraie bactériémie).",
    interpretation: "≥ 2 hémocultures concordantes = vraie bactériémie ; la salmonellose typhoïque se confirme par hémoculture la 1re semaine ; culture au-delà + antibiogramme guident le traitement ciblé.",
    anomalies: "Sepsis (staphylocoque, E. coli…), fièvre typhoïde, endocardite infectieuse, méningococcémie, infections liées aux cathéters.",
    limitations: "Négativisation rapide sous antibiotiques (prélever AVANT) ; contamination si asepsie imparfaite ; ne détecte pas les virus ni le paludisme (goutte épaisse !).",
    references: "HAS — hémocultures ; SPILF ; OMS — typhoïde.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "coproculture",
    name: "Coproculture / Examen parasitologique des selles",
    category: "biologie",
    definition: "Analyse des selles pour identifier bactéries pathogènes (culture) ou parasites et œufs (examen direct et concentré).",
    objective: "Diagnostiquer une diarrhée infectieuse (bactérienne ou parasitaire), une typhoïde tardive, ou rechercher du sang occulte selon le contexte.",
    indications: "Diarrhée aiguë glaireuse ou sanglante, diarrhée chronique, douleurs abdominales avec amaigrissement, retour de zone endémique, épidémie suspectée (choléra !).",
    contraindications: "Aucune.",
    preparation: "Recueillir frais dans un pot propre (noix suffit), éventuellement zone sanglante ou glaireuse ; de préférence avant antibiotiques.",
    procedureText: "Examen macroscopique, état frais (parasites mobiles), colorations, enrichissement et culture des germes ; rendu 48–72 h pour la coproculture.",
    materials: "Pot stérile propre, spatule ; milieux de culture et solutions de concentration.",
    parameters: "Germes pathogènes (salmonelles, shigelles, vibrions, campylobacters), parasites (amibes, giardia, ascaris, ankylostomes), œufs, sang, leucocytes.",
    referenceValues: "Repères usuels : flore digestive commensale normale ; PAS de salmonelle/shigelle/vibrion en état normal ; aucun parasite pathogène.",
    interpretation: "Isolement d'un pathogène = infection digestive confirmée, traitement ciblé ; parasite identifié → traitement antiparasitaire ; examen négatif n'élimine pas une cause virale (rotavirus).",
    anomalies: "Salmonelloses (dont typhoïde), shigellose, choléra, amibiase (abcès hépatique possible !), giardiase (malabsorption), helminthiases.",
    limitations: "Sensibilité dépendant du moment du prélèvement et de la quantité ; le choléra se confirme aussi par TDR en urgence ; virales non visibles ici.",
    references: "OMS — diarrhées et choléra ; HAS — diarrhées aiguës de retour de voyage.",
    updatedOn: "2026-08-15",
  },
  /* ==================== IMAGERIE MÉDICALE ==================== */
  {
    slug: "radiographie",
    name: "Radiographie (RX)",
    category: "imagerie",
    definition: "Image produite par les rayons X traversant le corps : les structures denses (os) apparaissent blanches, l'air noir.",
    objective: "Obtenir rapidement une image des os, du thorax ou de l'abdomen pour diagnostiquer fractures, infections pulmonaires ou occlusions.",
    indications: "Traumatisme (fracture, luxation), toux persistante et fièvre (pneumonie, tuberculose — fréquente au Togo), douleurs thoraciques, abdomen aigu (ASP), arthrose.",
    contraindications: "Grossesse (surtout 1er trimestre) : prévenir le personnel (protection plombée ou report de tout examen non urgent).",
    preparation: "Aucune pour la plupart ; retirer bijoux et objets métalliques ; une mammotubie n'est PAS une radiographie classique.",
    procedureText: "Position debout ou couché devant le capteur, quelques secondes d'immobilité, sans douleur, résultat immédiat.",
    materials: "Générateur de rayons X, capteur numérique, tabliers de plomb de protection.",
    parameters: "Incidences (face, profil…), qualité inspiratoire, exposition ; lecture par radiologue.",
    referenceValues: "Repères usuels : sans « valeurs » — lecture morphologique : transparence pulmonaire normale, alignement osseux sans solution de continuité, cœur < 50 % de la largeur thoracique (index cardiothoracique).",
    interpretation: "Condensation alvéolaire = pneumonie ; image apicale + toux chronique → tuberculose à confirmer (crachats/GeneXpert) ; trait de fracture ; épanchement pleural efface l'angle costodiaphragmatique.",
    anomalies: "Fractures, pneumonie, tuberculose, pleurésie, cardiomégalie, arthrose, corps étrangers, pneumopéritoine (occlusion/perforation).",
    limitations: "Faible sensibilité des tissus mous ; tuberculose débutante parfois invisible ; scanner ou échographie si doute ; rayonnement faible mais cumulatif.",
    references: "HAS — toux chronique et tuberculose ; OMS — TB ; SFR.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "echographie",
    name: "Échographie",
    category: "imagerie",
    definition: "Imagerie utilisant des ULTRASONS (aucun rayonnement) pour explorer les organes mous en temps réel.",
    objective: "Visualiser le foie, la vésicule, les reins, l'utérus, le fœtus, le cœur, la thyroïde, et guider des ponctions.",
    indications: "Douleurs abdominales ou pelviennes, ictère, suivi de grossesse (systématique : 3 échographies recommandées), masse, suspicion de lithiase, fièvre et masse hépatique (abcès amibien !).",
    contraindications: "Aucune — examen sans danger, y compris pendant la grossesse.",
    preparation: "Abdomen supérieur : jeûne 6 h (vésicule gorgée d'eau… non : à jeun !) ; pelvienne : VESSIE PLEINE (boire 1 L 1 h avant, ne pas uriner).",
    procedureText: "Gel sur la peau, sonde déplacée sur la région, 10–20 minutes, indolore, compte rendu immédiat possible.",
    materials: "Échographe, sondes convexe/linéaire/endocavitaire, gel de contact.",
    parameters: "Taille, échostructure des organes, liquide libre, mesures fœtales (DPA !), localisation placentaire.",
    referenceValues: "Repères usuels : sans valeur chiffrée générique ; foie homogène, pas de dilatation des voies biliaires, reins 9–12 cm sans dilatation pyélique.",
    interpretation: "Image liquidienne = kyste ou abcès ; calculs vésiculaires = arc hyperéchogène avec cône d'ombre ; début de grossesse suivie (sac, embryon, activité cardiaque).",
    anomalies: "Lithiase vésiculaire, kystes, abcès amibien du foie, grossesse extra-utérine (urgence !), fibromes, hydronéphrose, ascite.",
    limitations: "Opérateur-dépendant (la compétence de l'échographiste compte beaucoup) ; l'air digestif gêne ; compléter par scanner si doute.",
    references: "OMS — échographie obstétricale ; HAS ; SFR.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "scanner",
    name: "Scanner (TDM — tomodensitométrie)",
    category: "imagerie",
    definition: "Radiographie en coupes fines reconstruites par ordinateur, offrant une vue détaillée de tous les organes, avec ou sans injection de produit de contraste iodé.",
    objective: "Diagnostiquer précisément traumatismes, hémorragies, tumeurs, infections profondes ; travailler en urgence (AVC, polytraumatisme).",
    indications: "Traumatisme crânien ou abdominal, suspicion d'AVC, cancer (bilan d'extension), infection profonde, occlusion, embolie pulmonaire (angioscanner).",
    contraindications: "Injection iodée : insuffisance rénale (créatinine avant !), allergie à l'iode, grossesse ; hydratation avant/après.",
    preparation: "Jeûne 4–6 h si injection ; créatininémie récente obligatoire si contraste ; retirer métaux.",
    procedureText: "Allongé dans l'anneau, quelques secondes à minutes d'acquisition ; sensation de chaleur si injection (normale).",
    materials: "Scanner multicoupe, injecteur de produit iodé, verre de surveillance.",
    parameters: "Coupes (mm), densités (unités Hounsfield), temps artériel/veineux/tardif, reconstructions.",
    referenceValues: "Repères usuels : aucune normalité chiffrée générique ; lecture de morphologie et de densités par le radiologue.",
    interpretation: "Hyperdensité spontanée cérébrale = hémorragie ; prise de contraste en couronne = abcès ; thrombus artériel pulmonaire = défaut de rehaussement.",
    anomalies: "Hémorragies, fractures complexes, tumeurs, abcès profonds, embolies, occlusions, pancréatites graves.",
    limitations: "Irradiation supérieure à la RX (éviter les examens non justifiés, surtout enfants) ; risque rénal/allergique du contraste iodé.",
    references: "HAS — pertinence des examens d'imagerie ; SFR.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "irm",
    name: "IRM (Imagerie par Résonance Magnétique)",
    category: "imagerie",
    definition: "Imagerie utilisant un champ magnétique puissant et des ondes radio — sans rayons X — incomparable pour le cerveau, la moelle, les articulations et les tissus mous.",
    objective: "Détailler le système nerveux (AVC, tumeurs, sclérose en plaques), la colonne (hernies), les ligaments et ménisques, le pelvis profond.",
    indications: "AVC, épilepsie, tumeur cérébrale ou médullaire, hernie discale avec signes neurologiques, lésions sportives, endométriose, pelvi.",
    contraindications: "ABSOLUES ou relatives : pacemaker non compatible, clips cérébraux ferromagnétiques, corps étranger métallique (œil !), implants cocléaires anciens — QUESTIONNAIRE DE SÉCURITÉ OBLIGATOIRE. Gadolinium : prudence si insuffisance rénale sévère.",
    preparation: "Retirer TOUT métal (cartes, téléphone, bijoux) ; signalement de tout implant ; prévoir 30–60 min ; claustrophobie : prévenir (sédation possible).",
    procedureText: "Allongé immobile dans le tunnel (bruyant : bouchons fournis), séquences de 2–8 minutes, 20–45 min au total, indolore.",
    materials: "Aimant supraconducteur (1,5–3 T), antennes, consoles ; injecteur de gadolinium le cas échéant.",
    parameters: "Séquences T1, T2, FLAIR, diffusion (AVC !) ; mesures selon organe.",
    referenceValues: "Repères usuels : lecture morphologique sans normes chiffrées uniques ; l'hypersignal de diffusion est le signe précoce d'AVC ischémique (< 6 h).",
    interpretation: "Tumeur : masse avec prise de contraste et œdème ; hernie discale : bombement comprimant la racine ; démyélinisation : plaques T2 hyperintenses.",
    anomalies: "AVC, hernies discs, tumeurs, sclérose en plaques, ruptures ligamentaires/méniscales, moelle comprimée.",
    limitations: "Contre-indications magnétiques, disponibilité et coût, durée, fausse alarme possible ; scanner reste plus rapide en polytraumatisme.",
    references: "HAS ; SFR — sécurité IRM ; ACR Appropriateness Criteria.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "doppler",
    name: "Doppler (écho-Doppler vasculaire)",
    category: "imagerie",
    definition: "Échographie associée à l'analyse des flux sanguins (couleur, vitesses) dans les artères et les veines — sans rayonnement.",
    objective: "Rechercher un rétrécissement, un caillot (thrombose) ou un reflux, et mesurer la qualité de la circulation.",
    indications: "Jambe gonflée et douloureuse (TVP !), artérite (douleurs à la marche), HTA atypique (artère rénale), suivi carotidien (AVC), grossesse à risque (Doppler ombilical).",
    contraindications: "Aucune.",
    preparation: "Aucune ; peau propre ; une jambe TVP se manipule doucement.",
    procedureText: "Gel + sonde sur le trajet des vaisseaux, compression (signe clé de la TVP : veine non compressible), 15–30 min, indolore.",
    materials: "Échographe avec module Doppler couleur et pulsé, sonde linéaire haute fréquence.",
    parameters: "Vitesses systoliques, index de résistance, compressibilité veineuse, plaques et pourcentage de sténose.",
    referenceValues: "Repères usuels : veines spontanément compressibles et flux modulé par la respiration ; artères triphasiques au membre inférieur ; sténose carotide significative > 50–70 % (vitesses).",
    interpretation: "Veine incompressible échogène = TVP (risque d'embolie pulmonaire : urgence) ; flux monophasique distal = artérite ; index ombilical anormal = souffrance fœtale.",
    anomalies: "Thrombose veineuse, insuffisance veineuse, artérite/sténoses, athérome carotidien, microangiopathie rénale.",
    limitations: "Opérateur-dépendant ; veines profondes du mollet plus difficiles ; le Doppler veineux négatif avec forte suspicion → contrôle à 1 semaine.",
    references: "HAS — TVP et artérite ; AIUM/ISM — Doppler obstétrical.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "mammographie",
    name: "Mammographie",
    category: "imagerie",
    definition: "Radiographie spécialisée des seins avec compression douce, examen de référence du dépistage et du diagnostic des lésions mammaires.",
    objective: "Dépister le cancer du sein à un stade précoce (soignable dans la grande majorité des cas) et analyser une anomalie clinique.",
    indications: "Dépistage : à partir de 40–50 ans, régulièrement tous les 2 ans selon programmes ; diagnostic : nodule, écoulement, rétraction, asymétrie à tout âge (couplée à l'échographie < 35 ans).",
    contraindications: "Grossesse ; chez la jeune femme à sein dense : échographie en première intention.",
    preparation: "Venir sans crème ni poudre sous les aisselles ; de préférence hors période prémenstruelle (sensibilité).",
    procedureText: "Compression du sein quelques secondes par incidence (2 par sein), gêne brève mais essentielle à la qualité ; compte rendu BI-RADS.",
    materials: "Mammographe dédié (comprimeur, faible dose) ; lecture double idéale.",
    parameters: "Classification BI-RADS 0 à 6, masses, microcalcifications, distorsions.",
    referenceValues: "Repères usuels : BI-RADS 1–2 normal/bénin (contrôle de routine) ; BI-RADS 3 probablement bénin, contrôle à 6 mois ; BI-RADS 4–5 = biopsie nécessaire.",
    interpretation: "Microcalcifications groupées ou masse étoilée = suspicion ; BI-RADS 0 = examen incomplet → compléments (échographie, IRM).",
    anomalies: "Cancer du sein, kystes, fibroadénomes, mastose, abcès.",
    limitations: "Seins denses masquant les lésions ; irradiation faible ; ne remplace pas l'examen clinique ni l'autopalpation mensuelle conseillée.",
    references: "HAS/INCa — dépistage organisé ; ACR BI-RADS ; OMS — cancer du sein.",
    updatedOn: "2026-08-15",
  },
  /* ==================== EXAMENS CARDIOLOGIQUES ==================== */
  {
    slug: "ecg",
    name: "ECG (Électrocardiogramme)",
    category: "cardiologie",
    definition: "Enregistrement de l'activité électrique du cœur par des électrodes posées sur la peau — 12 dérivations en quelques secondes.",
    objective: "Diagnostiquer arythmies, infarctus, troubles de conduction et hypertrophies cardiaques ; examen de tout bilan cardiovasculaire.",
    indications: "Douleur thoracique, palpitations, malaise/syncope, dyspnée, bilan pré-opératoire, HTA, diabète, avant certains médicaments.",
    contraindications: "Aucune — examen indolore et sans danger.",
    preparation: "Allongé, au calme 5 min ; torse, poignets et chevilles découverts ; peau propre (rasage local si nécessaire).",
    procedureText: "Pose de 10 électrodes (membres + précordiales V1–V6), enregistrement de 10 secondes, impression immédiate du tracé.",
    materials: "Électrocardiographe, électrodes autocollantes, gel. Papier 25 mm/s, 10 mm/mV.",
    parameters: "Fréquence, rythme (sinusal ?), axe, PR, QRS, QT, ST, ondes T ; comparaison aux tracés anciens.",
    referenceValues: "Repères usuels : FC 60–100/min ; PR 120–200 ms ; QRS < 120 ms ; QTc < 440/450 ms ; P avant chaque QRS ampleur régulière.",
    interpretation: "Sus-décalage du segment ST = infarctus en cours (URGENCE ABSOLUE) ; absence d'onde P irrégulière = fibrillation auriculaire ; QRS larges réguliers rapides = tachycardie ventriculaire.",
    anomalies: "FA/flutter, BAV, BBG/BBD, SIV (ST sus), nécrose (ondes Q), péricardite (diffuse concave), HVG, troubles ioniques (K+ !).",
    limitations: "Examen instantané : un ECG de repos normal N'ÉLIMINE PAS un angor (épreuve d'effort/Holter) ; à refaire en série si douleur persistante.",
    references: "ESC — SIV et arythmies ; AHA/ACCF normalisation des tracés ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "echocardiographie",
    name: "Échocardiographie (ETT)",
    category: "cardiologie",
    definition: "Échographie du cœur associée au Doppler : mesure les cavités, l'épaisseur des parois, les valves et la fonction de pompe.",
    objective: "Évaluer la fraction d'éjection (FEVG), diagnostiquer valvulopathies, insuffisance cardiaque, épanchements et cardiopathies.",
    indications: "Souffle cardiaque, dyspnée, insuffisance cardiaque, HTA chronique, fièvre + souffle (endocardite), avant chirurgie cardiaque.",
    contraindications: "Aucune.",
    preparation: "Aucune préparation ; allongé côté gauche, torse nu.",
    procedureText: "Gel + sonde sur le thorax sous différentes incidences, 20–30 min, avec mesures Doppler des flux.",
    materials: "Échographe cardiaque avec sondes sectorielles.",
    parameters: "FEVG, diamètres VG/OG, VI, PAPs (pression artérielle pulmonaire), valves (fuites, sténoses), péricarde.",
    referenceValues: "Repères usuels : FEVG ≥ 50–55 % ; OG < 40 mm ; VI < 21 mm/m² ; PAPs < 35–40 mmHg.",
    interpretation: "FEVG effondrée = insuffisance cardiaque systolique ; fuite mitrale importante OG dilatée ; péricarde liquidien abondant = tamponnade si compression.",
    anomalies: "Insuffisance cardiaque, valvulopathies (rétrécissement/fuite), cardiomyopathies (hypertrophique, dilatée), HTAP, endocardite (végétations — TOE en complément).",
    limitations: "Fenêtres acoustiques parfois mauvaises ; l'ETT ne voit pas bien les coronaires (autres examens) ; besoin d'opérateur entraîné.",
    references: "ESC — insuffisance cardiaque et valvulopathies ; ASE (mesures).",
    updatedOn: "2026-08-15",
  },
  {
    slug: "holter-ecg",
    name: "Holter ECG (24–72 h)",
    category: "cardiologie",
    definition: "Enregistrement continu de l'ECG pendant 24 à 72 heures grâce à un petit appareil porté à la ceinture.",
    objective: "Capturer les arythmies intermittentes (palpitations, pauses) invisibles sur l'ECG de repos ; évaluer un traitement antiarythmique.",
    indications: "Palpitations, syncopes, vertiges, rythme irrégulier, évaluation de pacemaker, fibrillation paroxystique.",
    contraindications: "Aucune ; garder l'appareil au sec (pas de douche/effort de sudation intense).",
    preparation: "Porter des vêtements amples ; tenir un CARNET des horaires de symptômes et activités — indispensable à l'analyse.",
    procedureText: "Pose d'électrodes + enregistreur porté jour et nuit ; activité normale ; retour de l'appareil pour analyse informatique.",
    materials: "Enregistreur Holter, 3–7 électrodes, journal de bord.",
    parameters: "FC min/moyenne/max, pauses > 2 s, arythmies ventriculaires/supraventriculaires, corrélation symptômes-tracé.",
    referenceValues: "Repères usuels : FC diurne 60–100, nocturne 40–60 ; pauses < 2 s ; extrasystoles isolées rares chez le sujet sain.",
    interpretation: "L'essentiel est la CORRÉLATION symptomatique entre le carnet et les tracés ; pause > 3 s consciente ou BAV haut degré → orientation cardiologue urgent.",
    anomalies: "FA paroxystique, TV salvatrice, BAV, dysfonction sinuse, extrasystolie ventriculaire abondante.",
    limitations: "N'enregistre que la période portée (événements rarissimes : explore cardiaque implantable) ; conflits possible d'artéfacts de mouvement.",
    references: "ESC/ISHNE — Holter ; HAS — syncopes.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "holter-tensionnel",
    name: "Holter tensionnel (MAPA)",
    category: "cardiologie",
    definition: "Mesure Ambulatoire de la Pression Artérielle : brassard qui gonfle automatiquement toutes les 15–30 min pendant 24 h, jour et nuit.",
    objective: "Confirmer l'HTA, démasquer l'effet « blouse blanche » et l'HTA masquée, évaluer l'efficacité d'un traitement.",
    indications: "Chiffres TA élevés au cabinet, HTA résistante, hypotensions orthostatiques, grossesse à risque, suivi des hypertendus.",
    contraindications: "Aucune majeure (troubles du rythme irréguliers sévères peuvent fausser certaines mesures).",
    preparation: "Brassard adapté au bras ; garder le bras détendu pendant chaque mesure ; carnet des activités et horaires de sommeil.",
    procedureText: "Appareil porté 24 h à la ceinture ; mesures automatiques (± la nuit) ; analyse statistique des moyennes.",
    materials: "Tensiomètre ambulatoire, brassards, logiciel d'analyse.",
    parameters: "Moyennes TA 24 h / jour / nuit, % de dépassement, profil nycthéméral (dipper ou non), variabilité.",
    referenceValues: "Repères usuels : moyenne 24 h < 130/80 mmHg ; jour < 135/85 ; nuit < 120/70 ; chute nocturne physiologique 10–20 % (dipper).",
    interpretation: "Cabinet haut mais MAPA normale = effet blouse blanche (pas de surtraitement) ; MAPA haute et cabinet normal = HTA masquée (vrai risque) ; non-dipper = risque cardiovasculaire accru.",
    anomalies: "HTA blanche ou masquée, HTA résistante, dipper atténué (apnées du sommeil ?), hypotensions médicamenteuses.",
    limitations: "Gêne nocturne possible (sommeil) ; mesures de nuit manquantes si retrait ; ne remplace pas l'automesure à domicile régulière.",
    references: "ESC/ESH — HTA ; HAS — artérielle hypertension artérielle de la grossesse.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "epreuve-effort",
    name: "Épreuve d'effort",
    category: "cardiologie",
    definition: "ECG enregistré pendant un exercice gradué (tapis roulant ou vélo) pour démasquer une ischémie myocardique d'effort.",
    objective: "Rechercher un angor (artères coronaires rétréciesi), éprouver la capacité physique, expliquer des douleurs thoraciques ou une dyspnée.",
    indications: "Douleur thoracique d'effort, bilan avant reprise du sport (âge + facteurs de risque), suivi post-infarctus, évaluation d'une dyspnée.",
    contraindications: "ABSOLUES : infarctus récent (< 2 jours), angine instable, arythmie grave non contrôlée, sténose aortique serrée, myocardite aiguë, embolie pulmonaire aiguë. Toujours avec médecin et matériel de réanimation à proximité.",
    preparation: "Repas léger 2 h avant, vêtements et chaussures de sport, ne pas arrêter les médicaments sans avis (sauf éventuelles bêtabloquants demandés par le médecin).",
    procedureText: "Électrodes + brassard TA ; paliers croissants ; ARRÊT si douleur, sus-ST ≥ 2 mm, baisse de TA, troubles du rythme, essoufflement maximal.",
    materials: "Tapis/cycloergomètre, scope ECG, tensiomètre, chariot d'urgence (défibrillateur, oxygène).",
    parameters: "FC max théorique atteinte (220 − âge), sus-décalage ST, TA d'effort, capacité en METs, arythmies.",
    referenceValues: "Repères usuels : négative si ≥ 85 % de la FC max, pas de douleur, pas de sus-ST < 1 mm ; TA augmente régulièrement sans excès.",
    interpretation: "Sus-ST descendant ≥ 1 mm douloureux = ischémie → coronarographie discutée ; TA qui s'effondre à l'effort = mauvais pronostic, urgence d'évaluation.",
    anomalies: "Angor, ischémie silencieuse du diabétique, arythmies d'effort, HTA d'exercice, insuffisance de capacité aérobique.",
    limitations: "Sensibilité limitée (faux négatifs, notamment femmes jeunes) ; une épreuve négative n'élimine pas les petites plaques ; imagerie d'effort ou score calcique si doute.",
    references: "ESC — douleur thoracique chronique ; HAS ; AFC.",
    updatedOn: "2026-08-15",
  },
  /* ==================== EXPLORATIONS FONCTIONNELLES ==================== */
  {
    slug: "spirometrie",
    name: "Spirométrie / EFR",
    category: "explorations",
    definition: "Mesure des volumes et débits d'air respirés : on souffle à fond dans un embout après une inspiration maximale.",
    objective: "Distinguer trouble obstructif (asthme, BPCO) de trouble restrictif, quantifier sa sévérité et suivre la réponse au traitement.",
    indications: "Toux chronique, dyspnée, asthme, tabagisme (BPCO), bilan pré-opératoire thoracique, suivi de broncho-pneumopathies.",
    contraindications: "Relatives : infarctus récent, anévrisme, chirurgie ophtalmique ou thoracique récente, hémoptysie, pneumothorax.",
    preparation: "Pas de bronchodilatateur de courte durée 6–12 h ; pas de cigarette juste avant ; vêtements confortables ; position assise droite.",
    procedureText: "Pince-nez, inspiration maximale puis EXPIRATION FORTE ET TOTALE ≥ 6 secondes, 3 fois, courbes reproductibles ; ± test aux bronchodilatateurs.",
    materials: "Spiromètre étalonné, embouts à usage unique, pince-nez.",
    parameters: "VEMS, CVF, rapport VEMS/CVF, DEP (débit de pointe) ; courbes volume-temps et débit-volume.",
    referenceValues: "Repères usuels : VEMS et CVF ≥ 80 % de la prédite ; VEMS/CVF ≥ 70 % (ou au-delà de la limite inférieure de normalité).",
    interpretation: "VEMS/CVF abaissé + VEMS bas = obstructif (réversibilité ≥ 12 % et 200 mL = asthme) ; CVF basse et rapport normal = restrictif → compléter par CPT si disponible.",
    anomalies: "Asthme, BPCO (tabac !), bronchiectasies, fibroses, restriction neuro-musculaire ou par obésité sévère.",
    limitations: "Qualité dépend de l'effort du patient (enfants, fatigués) ; ne localise pas la cause : radiographie + clinique complètent.",
    references: "GOLD — BPCO ; GINA — asthme ; ATS/ERS — qualité des mesures.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "gaz-sang",
    name: "Gaz du sang artériel",
    category: "explorations",
    definition: "Analyse d'un prélèvement d'sang artériel mesurant l'oxygénation et l'équilibre acido-basique en temps quasi réel.",
    objective: "Évaluer la gravité d'une détresse respiratoire ou métabolique (asthme aigu, BPCO, acidose diabétique, sepsis) et guider l'oxygénothérapie.",
    indications: "Détresse respiratoire, coma, choc, intoxications, acidocétose, chirurgie majeure, ventilation mécanique.",
    contraindications: "Relatives : troubles de la coagulation, artère collatérale insuffisante (test d'Allen avant ponction radiale).",
    preparation: "Test d'Allen (retour de couleur de la main) ; patient au calme ; noter apport en O₂ et position.",
    procedureText: "Ponction de l'artère radiale au poignet (plus douloureuse qu'une ponction veineuse) avec seringue héparinée, analyse immédiate au gazomètre.",
    materials: "Seringue héparinée, aiguille fine, glace, gazomètre.",
    parameters: "pH, PaO₂, PaCO₂, HCO₃⁻, SaO₂ calculée, lactate le cas échéant.",
    referenceValues: "Repères usuels : pH 7,38–7,42 ; PaO₂ 80–100 mmHg ; PaCO₂ 38–42 mmHg ; HCO₃⁻ 22–26 mmol/L ; lactate < 2 mmol/L.",
    interpretation: "PaO₂ basse avec PaCO₂ basse/normale = hypoxémie simple ; PaCO₂ élevée = hypoventilation ; pH bas + HCO₃⁻ bas = acidose métabolique (diabétique, rénale, sepsis) ; toujours croiser avec la SpO₂ au doigt.",
    anomalies: "Asthme aigu grave, EPBPCO décompensée, embolie pulmonaire, acidocétose, états de choc, intoxication au CO.",
    limitations: "Photographie instantanée (répéter en détresse) ; ponction parfois ratée (sang veineux aspiré) ; corrélé obligatoirement à la clinique.",
    references: "ERS/ATS — insuffisance respiratoire ; SFAR/SRLF — détresses aiguës.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "eeg",
    name: "EEG (Électroencéphalogramme)",
    category: "explorations",
    definition: "Enregistrement de l'activité électrique du cerveau par des électrodes posées sur le cuir chevelu — l'examen clé de l'épilepsie.",
    objective: "Rechercher des décharges épileptiques, analyser des crises, des altérations de conscience ou des troubles du sommeil.",
    indications: "Crise convulsive ou suspicion d'épilepsie, absences, syncope atypique, encéphalopathie, coma, troubles du sommeil.",
    contraindications: "Aucune — indolore, sans rayonnement.",
    preparation: "Cheveux propres et secs (ni huile ni gel) ; parfois EEG en privation de sommeil (suivre la consigne) ; ne pas arrêter les antiépileptiques sans avis.",
    procedureText: "Allongé ou semi-assis, 20–40 min d'enregistrement au calme + hyperpnée (respirations profondes) + stimulation lumineuse, parfois sommeil.",
    materials: "Casque/électrodes, électroencéphalographe, photostimulation.",
    parameters: "Rythme de fond, symétrie, pointes/ondes lentes, réactivité, crises électriques.",
    referenceValues: "Repères usuels : rythme alpha postérieur réactif 8–12 Hz chez l'adulte éveillé ; absence de figures critiques.",
    interpretation: "Pointes-ondes focales = foyer épileptique ; pointes-ondes généralisées 3 Hz = absences typiques ; ralentissement diffus = encéphalopathie (métabolique, infectieuse).",
    anomalies: "Épilépsies focales ou généralisées, encéphalites, encéphalopathies métaboliques, états de mal non convulsifs.",
    limitations: "Un EEG intercritique NORMAL n'élimine pas l'épilepsie (à répéter/EEG sommeil ) ; les crises seuls se caractérisent cliniquement également.",
    references: "ILAE — classification des crises ; SEN/ANLCEF ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "emg",
    name: "EMG / ENMG",
    category: "explorations",
    definition: "Électroneuromyogramme : mesure des vitesses de conduction des nerfs et de l'activité électrique des muscles à l'aide d'électrodes et de stimulations.",
    objective: "Diagnostiquer neuropathies (canal carpien !), atteintes des racines (sciatique, cervicobrachialgie), maladies du muscle ou de la jonction neuro-musculaire.",
    indications: "Fourmillements des mains, faiblesse, amyotrophie, douleurs irradiantes, suspicion de neuropathie diabétique ou de SLA.",
    contraindications: "Relatives : troubles de la coagulation, pacemaker (partie stimulation à distance), plaie cutanée au site.",
    preparation: "Peau propre sans crème ; préciser les traitements ; examen en deux temps (conductions puis aiguille).",
    procedureText: "Petites stimulations électriques sur les trajets nerveux (30–45 min), puis fine aiguille dans certains muscles ; inconfortable mais bref.",
    materials: "Électromyographe, électrodes de surface, aiguilles concentriques stériles.",
    parameters: "Vitesses de conduction (m/s), amplitudes, latences distales, ondes F ; tracé d'effort musculaire.",
    referenceValues: "Repères usuels : VCN membre supérieur ≥ 50 m/s, membre inférieur ≥ 40 m/s ; latences distales normatives selon le nerf.",
    interpretation: "Latence distale médiane allongée + VCN ralentie = syndrome du canal carpien ; ralentissements diffus = polyneuropathie ; dénervation + fasciculations = atteinte du motoneurone.",
    anomalies: "Canal carpien, polyneuropathie diabétique ou alcoolique, radiculopathies L5/S1, myopathies, myasthénie, SLA.",
    limitations: "Douleur brève possible ; ne montre pas la cause (diabète ? carence ?) — biologie complémentaire ; normal précoce n'élimine pas.",
    references: "AANEM ; SFNP ; HAS — sciatiques et névralgies cervico-brachiales.",
    updatedOn: "2026-08-15",
  },
  /* ==================== ENDOSCOPIE ==================== */
  {
    slug: "fibroscopie",
    name: "Fibroscopie œsopho-gastro-duodénale (FOGD)",
    category: "endoscopie",
    definition: "Exploration de l'œsophage, de l'estomac et du duodénum par un tube souple à caméra introduit par la bouche.",
    objective: "Expliquer douleurs, reflux, anémie ou saignements digestifs hauts ; biopsier ; dépister H. pylori, ulcères, varices, cancers.",
    indications: "RGO persistant, dysphagie, douleurs épigastriques rebelles, vomissements ou selles noires, anémie ferriprive, cirrhose (varices), perte de poids.",
    contraindications: "Relatives : infarctus récent, instabilité cardio-respiratoire ; informer sur les anticoagulants/antiagrégants (biopsies).",
    preparation: "JEÛNE STRICT 6–8 h (ni boire ni manger) ; retirer prothèses dentaires ; prévoir un accompagnant si sédation.",
    procedureText: "Anesthésie locale de la gorge (± sédation courte), introduction douce, insufflation, examen 5–10 min, biopsies indolores possibles.",
    materials: "Fibroscope souple HD, anesthésique local en spray, pinces à biopsie.",
    parameters: "Aspect de la muqueuse, cardia, ulcérations, signes de H. pylori (biopsie), varices œsophagiennes graduées.",
    referenceValues: "Repères usuels : muqueuse rosée lisse, junction œso-gastrique en place, pas de lésion ni de stase.",
    interpretation: "Œsophagite (reflux), gastrite/ulcère + test H. pylori, varices graduées I–III (risque hémorragique), masse suspecte → biopsies.",
    anomalies: "Reflux gastro-œsophagien, ulcères, gastrite à H. pylori, varices de la cirrhose, cancers de l'estomac ou de l'œsophage.",
    limitations: "Ne traverse pas l'angle duodénal/jéjunum (entéroscopie si besoin) ; les lésions planes sont biopsiées pour confirmation histologique.",
    references: "HAS — endoscopie digestive haute ; ESGE ; SNFGE.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "coloscopie",
    name: "Coloscopie",
    category: "endoscopie",
    definition: "Exploration de la totalité du côlon et de l'extrémité iléale par un tube souple introduit par l'anus.",
    objective: "Dépister les polypes et le cancer colorectal (dès 50 ans ou antécédents), analyser des saignements ou une diarrhée chronique, retirer les polypes (prévention).",
    indications: "Dépistage cancer colorectal, rectorragies, anémie inexpliquée, diarrhée chronique, MICI, antécédents familiaux, polypose.",
    contraindications: "Colite grave aiguë, suspicion de perforation ; anticoagulants/antiagrégants : avis médical préalable (polypectomie).",
    preparation: "CLÉ DU SUCCÈS : régime sans résidus 48–72 h + solution évacuatrice (PEG) la veille et le matin, selles doivent être liquides claires ; jeûne 6 h.",
    procedureText: "Sous anesthésie générale courte ou sédation, 20–45 min, insufflation, recul progressif ; biopsies et polypectomie indolores.",
    materials: "Coloscope HD, CO₂ d'insufflation, pinces et anses diathermiques.",
    parameters: "Qualité de préparation (BBPS), intubation cæcale, lésions (taille, aspect, localisation), gestes réalisés.",
    referenceValues: "Repères usuels : muqueuse lisse vascularisée régulière, BBPS suffisant (≥ 6/9), pas de polype.",
    interpretation: "Polypes : retirés et analysés (adénome → surveillance à 3–5 ans) ; muqueuse ulcérée continue = rectocolite ; diverticules fréquents après 50 ans.",
    anomalies: "Polypes et cancer colorectal, MICI (RCH, Crohn), angiodysplasies, diverticulose, colites infectieuses.",
    limitations: "Dépend presque entièrement de la qualité de la préparation ; angles cécaux parfois difficiles à passer ; risque rare de perforation après polypectomie.",
    references: "ESGE — dépistage ; HAS/INCa — cancer colorectal ; SNFGE.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "bronchoscopie",
    name: "Bronchoscopie (fibroscopie bronchique)",
    category: "endoscopie",
    definition: "Exploration de la trachée et des bronches par un tube souple introduit par le nez ou la bouche.",
    objective: "Voir l'intérieur des voies aériennes, prélever (lavage, biopsies) pour cancers, infections (tuberculose à crachats négatifs !), hémoptysies.",
    indications: "Hémoptysie, opacité radiologique persistante, suspicion de cancer bronchique, tuberculose paucibacillaire, corps étranger, dilatation/aspiration.",
    contraindications: "Relatives : insuffisance respiratoire sévère non stabilisée, ischémie cardiaque aiguë ; créatinine si prélèvements importants saignants.",
    preparation: "Jeûne 6 h ; bilan coagulation si biopsies ; oxygène et scope de monitoring ; signature du consentement.",
    procedureText: "Anesthésie locale du nez/gorge ± sédation, progression douce, lavage broncho-alvéolaire, 10–20 min ; toux passagère ensuite.",
    materials: "Fibroscope bronchique, lidocaïne, aspirateur, pinces, flacons de LBA.",
    parameters: "Aspect des muqueuses, bourgeons, saignements, sténoses ; bactériologie/mycobactéries (GeneXpert !) et cytologie du LBA.",
    referenceValues: "Repères usuels : muqueuse rosée, carene fine et mobile, pas de bourgeon ni de sténose ; LBA stérile.",
    interpretation: "Bourgeon saignant = cancer suspecté → biopsie ; GeneXpert positif sur LBA = tuberculose confirmée même si crachats négatifs ; hémoptysie : localiser le segment saignant.",
    anomalies: "Cancers bronchiques, tuberculose, pneumonies atypiques, corps étrangers, bronchectasies, sarcoïdose.",
    limitations: "Ne voit pas les bronches distales fines (biopsie écho-guidée/scanner si besoin) ; des biopsies négatives n'éliminent pas formellement.",
    references: "ATS/ERS ; OMS — tuberculose ; SPLF ; HAS.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "cystoscopie",
    name: "Cystoscopie",
    category: "endoscopie",
    definition: "Exploration de l'urètre et de la vessie par un tube fin à caméra passant par les voies naturelles.",
    objective: "Rechercher la cause d'une hématurie, surveiller une tumeur vésicale, évaluer une obstruction (adénome prostatique) — gestes possibles (biopsies, extraction).",
    indications: "Sang dans les urines, infections récidivantes, tumeur vésicale (suivi), calculs, corps étrangers, urètre étroit.",
    contraindications: "Infection urinaire aiguë non traitée (ECBU préalable !), rétention aiguë drépanues.",
    preparation: "ECBU récent négatif ; vessie vidée juste avant ; toilette locale ; antibioprophylaxie selon terrain.",
    procedureText: "Gel anesthésique dans l'urètre, introduction du cystoscope souple, irrigation, examen 5–15 min ; brûlures mictionnelles 24 h possibles.",
    materials: "Cystoscope souple ou rigide, gel anesthésique, sérum d'irrigation, pinces.",
    parameters: "Urètre, col, parois vésicales, méats urétéraux, lésions ou calculs ; urines et lavages stérilité.",
    referenceValues: "Repères usuels : muqueuse lisse et rosée, trabéculation nulle, pas de tumeur ni de calcul.",
    interpretation: "Papillome/tumeur → biopsies et classification (TVNIM : surveillance cystoscopiques régulières) ; adénome : lobes comprimant le col ; lithiase : extraction.",
    anomalies: "Tumeurs vésicales, cystites chroniques, calculs, sténoses urétérales, hypertrophie prostatique.",
    limitations: "N'explore pas les reins/uretères (urétéroscopie) ; hématurie intermittente peut passer entre deux épisodes.",
    references: "EAU — hématurie et tumeurs vésicales ; AFU ; HAS.",
    updatedOn: "2026-08-15",
  },
  /* ==================== ANATOMOPATHOLOGIE ==================== */
  {
    slug: "biopsie",
    name: "Biopsie",
    category: "anapath",
    definition: "Prélèvement d'un fragment de tissu (peau, sein, prostate, foie...) pour analyse microscopique — examen qui POSE LE DIAGNOSTIC de certitude, notamment de cancer.",
    objective: "Affirmer la nature bénigne ou maligne d'une lésion, guider le traitement (grade, marqueurs) et le pronostic.",
    indications: "Masse ou nodule suspect, ulcération persistante, anomalies d'imagerie (BI-RADS 4–5, nodule), maladies inflammatoires du foie ou du rein, greffes.",
    contraindications: "Relatives selon le site : troubles de coagulation, infection cutanée au point de ponction ; antiagrégants/anticoagulants : adaptation préalable.",
    preparation: "Bilan TP/TCA/plaquettes si prélèvement profond ; anesthésie locale ; jeûne si ponction sous sédation.",
    procedureText: "Repérage clinique/échographique, anesthésie locale, prélèvement à l'aiguille ou à la pince (quelques mm), immersion immédiate au formol, rendu 5–15 jours.",
    materials: "Aiguilles (tru-cut, microbiopsie), pinces, flacon de formol tamponné bordereau d'accompagnement clinique complet (CRUCIAL).",
    parameters: "Nature du tissu, grade histologique, marges, marqueurs immuno-histochimiques (récepteurs…) selon l'organe.",
    referenceValues: "Repères usuels : tissu d'architecture normale ;'une anomalie décrite conduit au compte rendu anatomopathologique définitif.",
    interpretation: "« Prolifération atypique » ou « carcinome » = malignité selon le grade ; bénin = fibrome/inflammation ; insuffisant = à reprendre (on ne conclut jamais sur insuffisance).",
    anomalies: "Cancers, lésions précancéreuses, inflammations granulomateuses (TB !), stéatose/fibrose hépatique, glomérulonéphrites.",
    limitations: "Prélève parfois non représentatif (refaire si forte suspicion) ; délai d'analyse ; le rendu se discute en réunion de concertation (RCP).",
    references: "INCa — parcours cancers ; AFAQAP ; OMS classification des tumeurs.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "cytologie",
    name: "Cytologie (frottis, ponctions de liquides)",
    category: "anapath",
    definition: "Étude des CELLULES prélevées par frottis, brossage ou ponction d'un liquide (moins invasif qu'une biopsie tissulaire).",
    objective: "Dépister des cellules anormales (cancer du col de l'utérus par frottis !) ou analyser un épanchement (pleurale, ascite, ganglion).",
    indications: "Frottis cervico-utérin de dépistage (25–65 ans, tous les 3 ans après 2 normaux), nodule ganglionnaire ou thyroïdien (cytoponction), épanchements pleuraux/péritonéaux.",
    contraindications: "Aucune majeure ; frottis à distance des règles ; cytoponction : coagulation si profonde.",
    preparation: "FCV : pas de rapport ni de toilette interne 48 h ; ponction : repérage échographique.",
    procedureText: "Frottis : raclage doux du col avec brosse/é spatule ; cytoponction : fine aiguille dans le nodule ; cellules fixées et colorées, lecture au microscope.",
    materials: "Spéculum et brosse (FCV), aiguilles fines, lames, fixateurs ; lame de goutte épaisse selon liquide.",
    parameters: "Cellularity, atypies, classification (Bethesda pour le col et la thyroïde), cellules tumorales ou inflammatoires.",
    referenceValues: "Repères usuels : FCV Bethesda « négatif pour lésion » ; thyroïde Bethesda I–VI (I non contributif, VI carcinome) ; liquides : no tumoral cells.",
    interpretation: "Lésions de bas grade (LSIL/HSIL surveillance ou conisation) ; Bethesda IV/V/VI → chirurgie thyroïde discutée ; cellules malignes dans un épanchement = carcinose.",
    anomalies: "Lésions cervicales HPV (dépistage transforme le pronostic !), cancers thyroïdiens, métastases ganglionnaires, tuberculose ganglionnaire fréquente au Togo.",
    limitations: "Cellules isolées ≠ architecture (biopsie si doute) ; faux négatifs de drague ; le FCV dépend de la qualité du prélèvement.",
    references: "INCa — dépistage cancer du col ; Bethesda System ; OMS — HPV en Afrique.",
    updatedOn: "2026-08-15",
  },
  {
    slug: "histologie",
    name: "Histologie (analyse des coupes de tissu)",
    category: "anapath",
    definition: "Technique de laboratoire qui transforme une pièce anatomique (biopsie, pièce opératoire) en lames microscopiques colorées pour en étudier l'architecture cellulaire.",
    objective: "Confirmer un diagnostic précis, graduer les cancers, mesurer les marges d'exérèse, guider le traitement (RCP).",
    indications: "Toute pièce opératoire (appendicite !, myomas, tumorectomies), toute biopsie, placenta ou produit d'IVG/GEU, peau.",
    contraindications: "Aucune.",
    preparation: "Pièce AU FORMOL IMMÉDIATEMENT (10 volumes de formol pour 1 de tissu), bordereau clinique soigneusement rempli (renseignements = qualité du diagnostic).",
    procedureText: "Fixation 24–48 h, inclusion en paraffine, coupes de quelques microns, coloration HES, ± immuno-histochimie ; rendu 5–15 jours.",
    materials: "Formol, paraffine, microtome, colorations HES et spéciales (Gömöri, Ziehl…), microscopes.",
    parameters: "Nature et grade, infiltration/marges, embols vasculaires, périnévral, marqueurs (RE, HER2…), ADN mutational selon cancer.",
    referenceValues: "Repères usuels : architecture et cytologie conformes au tissu attendu ; marges saines > normes selon localisation.",
    interpretation: "« Marges envahies » = réintervention ou surveillance renforcée ; grade élevé = agressivité ; immuno-histochimie individuelise le traitement du cancer du sein.",
    anomalies: "Carcinomes et sarcomes gradués, tuberculose granulomateuse, parasitoses (schistosome), pathologie placentaire (môle !).",
    limitations: "Délai ; dépend du prélèvement ET des renseignements cliniques fournis ; immuno-histochimie parfois indisponible localement (transferts).",
    references: "OMS — classifications tumorales ; INCa ; AFAQAP.",
    updatedOn: "2026-08-15",
  },
];
